name: Teams Notification

on:
    pull_request:
        types: [opened]

jobs:
    notify:
        if: ${{ (contains(github.event.pull_request.labels.*.name, '.最優先') || contains(github.event.pull_request.labels.*.name, '.最優先(軽め)')) && contains(github.event.pull_request.title, '.FE') }}
        runs-on: ubuntu-latest
        steps:
            - name: Send notification to Teams
              run: |
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  PR_URL="${{ github.event.pull_request.html_url }}"
                  curl -X POST -H "Content-Type: application/json" \
                  -d "{
                    \"attachments\": [
                      {
                        \"contentType\": \"application/vnd.microsoft.card.adaptive\",
                        \"content\": {
                          \"\$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",
                          \"type\": \"AdaptiveCard\",
                          \"version\": \"1.2\",
                          \"body\": [
                            {
                              \"type\": \"TextBlock\",
                              \"text\": \"最優先のPRが投稿されました。\",
                              \"wrap\": true,
                              \"size\": \"Large\",
                              \"weight\": \"Bolder\"
                            },
                            {
                              \"type\": \"TextBlock\",
                              \"text\": \"${PR_TITLE}\",
                              \"wrap\": true,
                              \"size\": \"Large\",
                              \"weight\": \"Bolder\"
                            }
                          ],
                          \"actions\": [
                            {
                              \"type\": \"Action.OpenUrl\",
                              \"title\": \"PRを開く\",
                              \"url\": \"${PR_URL}\"
                            }
                          ]
                        }
                      }
                    ]
                  }" \
                  "https://prod-24.japaneast.logic.azure.com:443/workflows/b41994e7fd4e4f13aca10ed7d9248884/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=iXLpneNmROcpjwkX3YY4u6y88Qqr_JKa9Ek-T9ujjmg"
