name: Teams Notification

on:
    pull_request:
        types: [opened, edited, labeled]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send notification to Teams
              run: |
                  curl -X POST -H "Content-Type: application/json" \
                  -d '{"text": "A PR with a priority label has been created: ${{ github.event.pull_request.html_url }}"}' \
                  https://prod-24.japaneast.logic.azure.com:443/workflows/b41994e7fd4e4f13aca10ed7d9248884/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=iXLpneNmROcpjwkX3YY4u6y88Qqr_JKa9Ek-T9ujjmg
